### ISSUE TITLE
Error in parsing R file during install_github(repo = "Zelazny7/binnr")

### ISSUE THREAD

**Issue by m-dz** [Zelazny7/binnr#2]
My apologies, problem solved by adamryczkowski's pull request.

**Comment by gravesee** [comment]
Thanks, I think it's just an artifact from working on my Mac. I have an updated package called binnr2 that is more smartly coded. Let me know what features you use and I'll try to add them

**Comment by m-dz** [comment]
Maybe you would like to pull the adamryczkowski's amendment for that? His fork of binnr installed smoothly.

Would it be okay for you to send you handful of questions on the binning, WoE-substitution and LASSO subject via email?

**Comment by gravesee** [comment]
Sure, here's my email address: gravcon5@gmail.com

And here's Binnr2: https://github.com/Zelazny7/binnr2/tree/develop
